dist: trusty
sudo: required
language: c
script:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y libelf-dev linux-headers-$(uname -r)"
  - "git clone https://github.com/netmap-unipi/netmap"
  - "cd netmap && ./configure --no-drivers && make && sudo make install"
  - "cd codelab && make"
  - "cd solutions && make"
